const express=require("express");const crypto=require("crypto");const fs=require("fs");const path=require("path");
const app=express();app.use(express.json());app.use(express.static(path.join(__dirname,"public")));const PORT=process.env.PORT||5000;
const FILE=path.join(__dirname,"owner-data.json");const OWNER_USER=process.env.OWNER_USERNAME||"dangerowner";const OWNER_PASS=process.env.OWNER_PASSWORD||"ChangeMe@2026";const COOKIE="danger_owner";const sessions=new Map();
function load(){try{return JSON.parse(fs.readFileSync(FILE,"utf8"))}catch{return{panels:[],logs:[]}}}function save(d){fs.writeFileSync(FILE,JSON.stringify(d,null,2))}function sid(){return crypto.randomBytes(32).toString("hex")}function token(){return crypto.randomBytes(32).toString("hex")}function hash(x){return crypto.createHash("sha256").update(x).digest("hex")}function auth(req,res,next){const s=req.headers.cookie?.match(new RegExp(COOKIE+"=([^;]+)"))?.[1];if(!s||!sessions.has(s)||sessions.get(s)<Date.now())return res.status(401).json({error:"Unauthorized"});next()}function log(d,id,action,details){d.logs.unshift({id:Date.now().toString(36)+Math.random().toString(36).slice(2),panelId:id,action,details,createdAt:new Date().toISOString()});d.logs=d.logs.slice(0,300)}
app.post("/api/login",(req,res)=>{if(req.body.username!==OWNER_USER||req.body.password!==OWNER_PASS)return res.status(401).json({error:"Invalid credentials"});const s=sid();sessions.set(s,Date.now()+86400000);res.setHeader("Set-Cookie",COOKIE+"="+s+"; HttpOnly; SameSite=Lax; Path=/; Max-Age=86400");res.json({ok:true})});
app.post("/api/logout",auth,(req,res)=>{const s=req.headers.cookie?.match(new RegExp(COOKIE+"=([^;]+)"))?.[1];sessions.delete(s);res.setHeader("Set-Cookie",COOKIE+"=; HttpOnly; Path=/; Max-Age=0");res.json({ok:true})});
app.get("/api/panels",auth,(req,res)=>res.json(load().panels));
app.post("/api/panels",auth,(req,res)=>{const d=load(),{name,url,days=30}=req.body;if(!name||!url)return res.status(400).json({error:"Name and URL required"});const raw=token(),p={id:crypto.randomUUID(),name,url,controlTokenHash:hash(raw),status:"active",expiresAt:new Date(Date.now()+Number(days)*86400000).toISOString(),createdAt:new Date().toISOString(),lastSeenAt:null};d.panels.unshift(p);log(d,p.id,"created","Panel created by owner");save(d);res.json({...p,controlToken:raw})});
app.post("/api/panels/:id/block",auth,(req,res)=>changeStatus(req,res,"blocked"));app.post("/api/panels/:id/unblock",auth,(req,res)=>changeStatus(req,res,"active"));
function changeStatus(req,res,status){const d=load(),p=d.panels.find(x=>x.id===req.params.id);if(!p)return res.status(404).json({error:"Panel not found"});p.status=status;log(d,p.id,status==="blocked"?"blocked":"unblocked","Owner changed panel status");save(d);res.json({ok:true})}
app.post("/api/panels/:id/extend",auth,(req,res)=>{const d=load(),p=d.panels.find(x=>x.id===req.params.id);if(!p)return res.status(404).json({error:"Panel not found"});const days=Math.max(1,Number(req.body.days||30));const base=Math.max(Date.now(),new Date(p.expiresAt).getTime());p.expiresAt=new Date(base+days*86400000).toISOString();log(d,p.id,"extended",days+" days");save(d);res.json(p)});
app.patch("/api/panels/:id",auth,(req,res)=>{const d=load(),p=d.panels.find(x=>x.id===req.params.id);if(!p)return res.status(404).json({error:"Panel not found"});for(const k of ["name","url","status","expiresAt"])if(req.body[k]!==undefined)p[k]=req.body[k];log(d,p.id,"updated",JSON.stringify(req.body));save(d);res.json(p)});
app.delete("/api/panels/:id",auth,(req,res)=>{const d=load(),i=d.panels.findIndex(x=>x.id===req.params.id);if(i<0)return res.status(404).json({error:"Panel not found"});d.panels.splice(i,1);log(d,req.params.id,"deleted","Panel deleted by owner");save(d);res.json({ok:true})});
app.get("/api/logs",auth,(req,res)=>res.json(load().logs));
app.get("/api/control/status",(req,res)=>{const raw=req.headers["x-panel-token"];if(!raw)return res.status(401).json({active:false});const d=load(),p=d.panels.find(x=>x.controlTokenHash===hash(raw));if(!p)return res.status(401).json({active:false});p.lastSeenAt=new Date().toISOString();save(d);res.json({active:p.status==="active"&&new Date(p.expiresAt)>new Date(),status:p.status,expiresAt:p.expiresAt})});
app.get("*",(req,res)=>res.sendFile(path.join(__dirname,"public/index.html")));
app.listen(PORT,"0.0.0.0",()=>console.log("DANGER OWNER PANEL running on "+PORT));
