const express=require("express");const crypto=require("crypto");const {Pool}=require("pg");const path=require("path");
const app=express();app.use(express.json());app.use(express.static(path.join(__dirname,"public")));const PORT=process.env.PORT||5000;
const pool=new Pool({connectionString:process.env.DATABASE_URL,ssl:process.env.DATABASE_URL?{rejectUnauthorized:false}:false});
const OWNER_USER=process.env.OWNER_USERNAME||"dangerowner";const OWNER_PASS=process.env.OWNER_PASSWORD||"ChangeMe@2026";const COOKIE="danger_owner";const sessions=new Map();
async function init(){await pool.query("CREATE EXTENSION IF NOT EXISTS pgcrypto");await pool.query("CREATE TABLE IF NOT EXISTS panels(id UUID PRIMARY KEY DEFAULT gen_random_uuid(),name TEXT NOT NULL,url TEXT NOT NULL,token_hash TEXT NOT NULL UNIQUE,status TEXT NOT NULL DEFAULT 'active',expires_at TIMESTAMPTZ NOT NULL,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),last_seen_at TIMESTAMPTZ)");await pool.query("CREATE TABLE IF NOT EXISTS panel_logs(id BIGSERIAL PRIMARY KEY,panel_id UUID,action TEXT NOT NULL,details TEXT,created_at TIMESTAMPTZ NOT NULL DEFAULT NOW())")}
const sid=()=>crypto.randomBytes(32).toString("hex"),token=()=>crypto.randomBytes(32).toString("hex");
function auth(req,res,next){const s=req.headers.cookie?.match(new RegExp(COOKIE+"=([^;]+)"))?.[1];if(!s||!sessions.has(s)||sessions.get(s)<Date.now())return res.status(401).json({error:"Unauthorized"});next()}
app.post("/api/login",(req,res)=>{if(req.body.username!==OWNER_USER||req.body.password!==OWNER_PASS)return res.status(401).json({error:"Invalid credentials"});const s=sid();sessions.set(s,Date.now()+86400000);res.setHeader("Set-Cookie",COOKIE+"="+s+"; HttpOnly; SameSite=Lax; Path=/; Max-Age=86400");res.json({ok:true})});
app.post("/api/logout",auth,(req,res)=>{const s=req.headers.cookie?.match(new RegExp(COOKIE+"=([^;]+)"))?.[1];sessions.delete(s);res.setHeader("Set-Cookie",COOKIE+"=; HttpOnly; Path=/; Max-Age=0");res.json({ok:true})});
app.get("/api/panels",auth,async(req,res)=>res.json((await pool.query("SELECT id,name,url,status,expires_at,created_at,last_seen_at FROM panels ORDER BY created_at DESC")).rows));
app.post("/api/panels",auth,async(req,res)=>{const{name,url,days=30}=req.body;if(!name||!url)return res.status(400).json({error:"Name and URL required"});const t=token(),h=crypto.createHash("sha256").update(t).digest("hex");const q=await pool.query("INSERT INTO panels(name,url,token_hash,expires_at) VALUES($1,$2,$3,NOW()+($4||' days')::interval) RETURNING id,name,url,status,expires_at,created_at",[name,url,h,Number(days)]);const p=q.rows[0];await pool.query("INSERT INTO panel_logs(panel_id,action,details) VALUES($1,$2,$3)",[p.id,"created","Panel created by owner"]);res.json({...p,controlToken:t})});
app.patch("/api/panels/:id",auth,async(req,res)=>{const allowed=["name","url","status","expires_at"],parts=[],vals=[];for(const k of allowed)if(req.body[k]!==undefined){vals.push(req.body[k]);parts.push(k+"=$"+vals.length)}if(!parts.length)return res.status(400).json({error:"Nothing to update"});vals.push(req.params.id);const q=await pool.query("UPDATE panels SET "+parts.join(",")+" WHERE id=$"+vals.length+" RETURNING id,name,url,status,expires_at,created_at,last_seen_at",vals);if(!q.rowCount)return res.status(404).json({error:"Panel not found"});await pool.query("INSERT INTO panel_logs(panel_id,action,details) VALUES($1,$2,$3)",[req.params.id,"updated",JSON.stringify(req.body)]);res.json(q.rows[0])});
app.post("/api/panels/:id/block",auth,async(req,res)=>{const q=await pool.query("UPDATE panels SET status='blocked' WHERE id=$1 RETURNING id",[req.params.id]);if(!q.rowCount)return res.status(404).json({error:"Panel not found"});await pool.query("INSERT INTO panel_logs(panel_id,action,details) VALUES($1,$2,$3)",[req.params.id,"blocked","Blocked by owner"]);res.json({ok:true})});
app.post("/api/panels/:id/unblock",auth,async(req,res)=>{const q=await pool.query("UPDATE panels SET status='active' WHERE id=$1 RETURNING id",[req.params.id]);if(!q.rowCount)return res.status(404).json({error:"Panel not found"});await pool.query("INSERT INTO panel_logs(panel_id,action,details) VALUES($1,$2,$3)",[req.params.id,"unblocked","Unblocked by owner"]);res.json({ok:true})});
app.post("/api/panels/:id/extend",auth,async(req,res)=>{const days=Math.max(1,Number(req.body.days||30));const q=await pool.query("UPDATE panels SET expires_at=GREATEST(expires_at,NOW())+($2||' days')::interval WHERE id=$1 RETURNING id,name,url,status,expires_at,created_at,last_seen_at",[req.params.id,days]);if(!q.rowCount)return res.status(404).json({error:"Panel not found"});await pool.query("INSERT INTO panel_logs(panel_id,action,details) VALUES($1,$2,$3)",[req.params.id,"extended",days+" days"]);res.json(q.rows[0])});
app.delete("/api/panels/:id",auth,async(req,res)=>{await pool.query("DELETE FROM panel_logs WHERE panel_id=$1",[req.params.id]);const q=await pool.query("DELETE FROM panels WHERE id=$1",[req.params.id]);if(!q.rowCount)return res.status(404).json({error:"Panel not found"});res.json({ok:true})});
app.get("/api/control/status",async(req,res)=>{const raw=req.headers["x-panel-token"];if(!raw)return res.status(401).json({active:false});const h=crypto.createHash("sha256").update(raw).digest("hex");const q=await pool.query("SELECT id,status,expires_at FROM panels WHERE token_hash=$1",[h]);if(!q.rowCount)return res.status(401).json({active:false});const p=q.rows[0];await pool.query("UPDATE panels SET last_seen_at=NOW() WHERE id=$1",[p.id]);res.json({active:p.status==="active"&&new Date(p.expires_at)>new Date(),status:p.status,expiresAt:p.expires_at})});
app.get("/api/logs",auth,async(req,res)=>res.json((await pool.query("SELECT l.*,p.name panel_name FROM panel_logs l LEFT JOIN panels p ON p.id=l.panel_id ORDER BY l.created_at DESC LIMIT 100")).rows));
app.get("*",(req,res)=>res.sendFile(path.join(__dirname,"public/index.html")));
init().then(()=>app.listen(PORT,"0.0.0.0",()=>console.log("DANGER OWNER PANEL running on "+PORT))).catch(e=>{console.error(e);process.exit(1)});